[project]
name = "ssyk4-scb-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "icecream>=2.1.10",
    "matplotlib>=3.10.8",
    "pathlib>=1.0.1",
    "polars>=1.38.0",
    "pyscbwrapper>=0.1.2",
]
