[project]
name = "daioe-ex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "icecream>=2.1.10",
    "jupyter>=1.1.1",
    "pathlib>=1.0.1",
    "polars>=1.38.1",
]
